apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-certs
  namespace: traefik
  labels:
    app: traefik-ingress
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 32Mi
