apiVersion: v1
kind: Secret
metadata:
  name: traefik-dashboard-authentication
  namespace: traefik
type: Opaque
stringData:
  #traefik/traefik
  traefik-dashboard-authentication: traefik:$apr1$X5L/agsv$Xdl0K/2IAHPefA.5jkKZo.
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-authentication
  namespace: traefik
type: Opaque
stringData:
  #wordpress/traefik
  traefik-dashboard-authentication: wordpress:$apr1$X5L/agsv$Xdl0K/2IAHPefA.5jkKZo.
